### ISSUE TITLE
error occurs in 2 simliar routers name

### ISSUE THREAD

**Issue by orangemi** [toajs/toa-router#4]
Define 2 routers named `/abc` and `/abcd`. Then visit `/abcd`. it will throw internal server error.

Example:
```js
'use strict'
const toa = require('toa')
const Router = require('toa-router')
const app = toa()

const router1 = new Router('/abc')
router1.get('/:anything', function () {
  this.body = 'ok'
})

const router2 = new Router('/abcd')
router2.get('/:anything', function () {
  this.body = 'ok'
})

app.use(router1.toThunk())
app.use(router2.toThunk())

app.listen(3000)
```

Error:
```
  Error: Path is not start with "/": "d"
      at Trie.match (/Users/Orange/projects/teambition/playground/toa-router-sample/node_modules/route-trie/index.js:50:13)
      at Context.<anonymous> (/Users/Orange/projects/teambition/playground/toa-router-sample/node_modules/toa-router/index.js:61:33)
      at Generator.next (<anonymous>)
```

**Comment by zensh** [comment]
`v2.1.1` released
